// Scripted answers for the Monitoring Agent chat. Nothing here is generated by a model.
// Answers point to evidence and cite record IDs. They never settle a disputed fact.

import { breakDifference, holdingSpec, recordId, type ViewModel } from '../data/derive';
import { fmtCr, fmtInt, fmtLakh, fmtPct, fmtPrice, fmtTime, fmtAge } from '../data/format';
import { LIMITS, type Break, type Proposal, type Verdict } from '../data/scenario';
import type { Selection } from './store';
import type { AgentId } from '../data/scenario';

export interface Scripted {
  question: string;
  keywords: string[];
  answer: (vm: ViewModel) => string;
}

/** Record IDs written as [[ID]] become links in the chat answer. */
const L = (id: string) => `[[${id}]]`;

/**
 * A link to an event by its authoring key. The log is renumbered per state, so
 * an answer can never name a display ID of its own.
 */
const E = (vm: ViewModel, key: string) => L(recordId(vm, key));

const proposalOf = (vm: ViewModel, id: string) =>
  [...vm.open, ...vm.closed].find((i) => i.id === id)?.decision as Proposal | undefined;
const verdictOf = (vm: ViewModel, id: string) =>
  [...vm.open, ...vm.closed].find((i) => i.id === id)?.decision as Verdict | undefined;

const MONITOR: Scripted[] = [
  {
    question: 'Is any feed late?',
    keywords: ['feed', 'late', 'stale', 'data'],
    answer: (vm) =>
      vm.health.allLive
        ? `All ${vm.health.total} feeds are live. The oldest is ${vm.feeds.slice().sort((a, b) => b.ageSec - a.ageSec)[0].name}, updated ${fmtAge(vm.feeds.slice().sort((a, b) => b.ageSec - a.ageSec)[0].lastUpdatedMs, vm.nowMs)} ago, which is inside its normal cadence.`
        : `${vm.health.lateFeeds.map((f) => `${f.name} stopped updating at ${fmtTime(f.lastUpdatedMs)} (${Math.floor(f.ageSec / 60)} min ago)`).join('; ')}. Agents that depend on it: ${vm.health.lateFeeds.flatMap((f) => f.dependents).map((a) => vm.agents[a].name).filter((v, i, arr) => arr.indexOf(v) === i).join(', ')}. See ${L(vm.monitorFlags.find((f) => f.kind === 'late')?.id ?? 'EVT-0001')}.`,
  },
  {
    question: 'What did you flag since 09:15?',
    keywords: ['flag', 'since', 'morning', 'happened'],
    answer: (vm) =>
      vm.monitorFlags.length
        ? vm.monitorFlags.map((f) => `${fmtTime(f.atMs)} ${f.text} (${L(f.id)})`).join(' · ')
        : 'Nothing flagged since the market opened at 09:15.',
  },
  {
    question: 'Which agent acted last?',
    keywords: ['last', 'acted', 'silent', 'quiet', 'action'],
    answer: (vm) => `${vm.lastAction.agent}, ${fmtAge(vm.lastAction.atMs, vm.nowMs)} ago: ${vm.lastAction.text}. Silence turns amber after 10 min during market hours.`,
  },
];

const INFOSYS: Scripted[] = [
  {
    question: 'Why did this come to me?',
    keywords: ['why', 'come', 'reach', 'escalat', 'me'],
    answer: (vm) => {
      const d = proposalOf(vm, 'DEC-0911-01');
      const [hi, lo] = d ? d.conflict.sides : [];
      return `The proposal is inside every limit, but its case rests on ${d?.conflict.fact ?? 'a disputed fact'}, and the two sources disagree: management ${hi?.value} (${L('SRC-INF-01')}) and Tarang Research ${lo?.value} (${L('SRC-INF-02')}). The autonomy rules send any proposal built on a disputed fact to a person. The Risk Agent recorded that at ${E(vm, 'EVT-0080')}.`;
    },
  },
  {
    question: 'Which growth number is right?',
    keywords: ['right', 'correct', 'which', 'believe', 'growth', 'trust', 'true'],
    answer: (vm) => {
      const d = proposalOf(vm, 'DEC-0911-01');
      const [hi, lo] = d ? d.conflict.sides : [];
      return `The record holds two figures and no resolution: ${hi?.value} from the Q1 FY27 call (${L('SRC-INF-01')}) and ${lo?.value} from the 2 Sep sector note (${L('SRC-INF-02')}). The Research Agent has not picked one, and neither will I. The next check is the Q2 FY27 results in mid-October; the proposal names what would prove it wrong.`;
    },
  },
  {
    question: 'What changed between version 1 and 2?',
    keywords: ['version', 'changed', 'v1', 'v2', 'cut', 'size'],
    answer: (vm) => {
      const d = proposalOf(vm, 'DEC-0911-01');
      const [v1, v2] = d ? d.versions : [];
      return `Version 1 sized the position at ${fmtCr(v1?.amount ?? 0)} at ${fmtTime(Date.parse(v1?.at ?? ''))} (${E(vm, 'EVT-0069')}). Version 2 cut it to ${fmtCr(v2?.amount ?? 0)} at ${fmtTime(Date.parse(v2?.at ?? ''))} (${E(vm, 'EVT-0075')}) under the Portfolio Agent's rule that a first position is capped at ${fmtPct(LIMITS.firstPositionPct, 0)} of the fund until the next results. The evidence and the disagreement did not change.`;
    },
  },
  {
    question: 'What happens if I do nothing?',
    keywords: ['nothing', 'expire', 'timer', 'happens'],
    answer: (vm) => {
      const item = vm.open.find((i) => i.id === 'DEC-0911-01');
      return item ? `At ${fmtTime(item.deadlineMs!)} the proposal expires and nothing is bought. Cash stays at ${fmtCr(vm.fund.cash)}. The expiry is written to the record.` : 'The proposal is closed; see the record for the outcome.';
    },
  },
];

const HDFC: Scripted[] = [
  {
    question: 'Where exactly do Bull and Bear split?',
    keywords: ['split', 'disagree', 'differ', 'where'],
    answer: (vm) =>
      `On one assumption: whether deposit growth recovers in the second half of the year. Bull rests on the August system deposit data (${L('SRC-HDB-02')}) and management's Q1 call (${L('SRC-HDB-05')}). Bear rests on the 28 Aug Tarang note (${L('SRC-HDB-03')}) and the 9 Sep rate increase (${L('SRC-HDB-04')}). Both use the Q1 FY27 filing (${L('SRC-HDB-01')}). The cases are at ${E(vm, 'EVT-0910-05')} and ${E(vm, 'EVT-0910-06')}.`,
  },
  {
    question: 'What does Bull’s size do to the Banking limit?',
    keywords: ['banking', 'limit', 'sector', 'room', 'headroom'],
    answer: (vm) => {
      const item = vm.open.find((i) => i.id === 'DEC-0911-02');
      const d = verdictOf(vm, 'DEC-0911-02');
      const bull = item?.previews.find((p) => p.key === 'bull');
      const sector = vm.fund.sectors.find((s) => s.name === holdingSpec(d?.ticker ?? '')?.sector);
      return bull && sector && d
        ? `${sector.name} is ${fmtPct(sector.pct)} of the fund now with ${fmtCr(sector.headroom)} of room under its ${fmtPct(sector.limitPct, 0)} limit. Bull's ${fmtCr(d.bull.amount)} takes it to ${fmtPct(bull.sectorPct)}, which is ${fmtPct(bull.sectorUsedPct, 0)} of the limit. Halfway takes it to ${fmtPct(item!.previews.find((p) => p.key === 'halfway')!.sectorPct)}.`
        : 'The verdict is closed; see the record for the outcome.';
    },
  },
  {
    question: 'Why is the Portfolio Agent waiting?',
    keywords: ['portfolio', 'waiting', 'agent', 'size'],
    answer: (vm) => `It cannot size an add while Bull and Bear disagree on the size, so it set itself to Waiting at ${fmtTime(vm.agents.portfolio.changedAtMs ?? vm.nowMs)} (${E(vm, 'EVT-0073')}). Any of the four choices here releases it.`,
  },
];

const AXIS: Scripted[] = [
  {
    question: 'What exactly does not match?',
    keywords: ['match', 'mismatch', 'difference', 'what'],
    answer: (vm) => {
      const d = [...vm.open, ...vm.closed].find((i) => i.kind === 'break')?.decision as Break | undefined;
      if (!d) return 'The mismatch is closed; see the record for the outcome.';
      const diff = breakDifference(d);
      return `Our trade record ${L(d.tradeId)} says ${fmtInt(d.ourShares)} Axis Bank shares were sold on 10 Sep. The broker's contract note (${L('SRC-AXS-01')}) shows ${fmtInt(d.brokerShares)}. The ${fmtInt(diff.shares)}-share difference is about ${fmtLakh(diff.rupees)} at that day's price of ${fmtPrice(d.price)}. The Operations Agent raised it at ${E(vm, 'EVT-0066')}.`;
    },
  },
  {
    question: 'Why is it due at 18:00?',
    keywords: ['due', '18:00', 'deadline', 'why'],
    answer: (vm) => {
      const d = [...vm.open, ...vm.closed].find((i) => i.kind === 'break')?.decision as Break | undefined;
      const shares = d ? fmtInt(breakDifference(d).shares) : 'some';
      return `The fund administrator strikes today's official value per unit after the close. An open mismatch means the books it works from could be wrong by ${shares} shares, so the break has to be settled or owned before then.`;
    },
  },
  {
    question: 'What does accepting the broker’s record change?',
    keywords: ['accept', 'broker', 'change', 'books'],
    answer: (vm) => {
      const d = [...vm.open, ...vm.closed].find((i) => i.kind === 'break')?.decision as Break | undefined;
      if (!d) return 'The mismatch is closed; see the record for the outcome.';
      const diff = breakDifference(d);
      return `Our books would show ${fmtInt(diff.shares)} more Axis Bank shares held and ${fmtLakh(diff.rupees)} less cash received. The fund value barely moves, because the shares are worth about what the cash was. The correction is written to the record with your reason.`;
    },
  },
];

const FEED_LATE: Scripted[] = [
  {
    question: 'Which agents are affected?',
    keywords: ['agent', 'affected', 'depend', 'paused'],
    answer: (vm) => {
      const late = vm.health.lateFeeds[0];
      return late ? `${late.dependents.map((a) => vm.agents[a].name).join(', ')} depend on ${late.name}. Under the standing rule, agents that depend on a feed stale for 10 min are paused: ${E(vm, 'EVT-0086')}.` : 'No feed is late now.';
    },
  },
  {
    question: 'Which numbers on screen are stale?',
    keywords: ['number', 'stale', 'screen', 'value'],
    answer: (vm) => `Fund value, value per unit, drawdown and every limit use NSE prices last updated at ${fmtTime(vm.fund.measuredAtMs)}. They are shown grey with that time. Cash and the order counts come from the orders feed, which is live.`,
  },
];

const LIMIT_OVER: Scripted[] = [
  {
    question: 'Did an agent trade into this?',
    keywords: ['trade', 'agent', 'cause', 'why', 'how'],
    answer: (vm) => {
      const row = vm.limits.broken[0];
      return `No. The Risk Agent recorded at ${E(vm, 'EVT-0077')} that bank prices rose and no agent traded. A broken limit stops agents adding to ${row ? row.name.replace(' sector', '') : 'it'}; it never forces a sale.`;
    },
  },
  {
    question: 'What can I do about it?',
    keywords: ['do', 'option', 'fix', 'trim'],
    answer: () => `Three things, and none is required today: leave it and let prices move, ask the Portfolio Agent for a trim proposal, or raise the limit on the Rules page, which is a logged rule change.`,
  },
];

function agentScripts(id: AgentId): Scripted[] {
  return [
    {
      question: 'What is it doing right now?',
      keywords: ['doing', 'now', 'working'],
      answer: (vm) => `${vm.agents[id].name}: ${vm.agents[id].liveLine}. Status: ${vm.agents[id].statusLine}.`,
    },
    {
      question: 'What has it done since 09:15?',
      keywords: ['done', 'since', 'today', 'count', 'morning'],
      answer: (vm) => {
        const a = vm.agents[id];
        const recent = a.recent.slice(0, 3).map((e) => `${fmtTime(Date.parse(e.at))} ${e.text} (${L(e.id)})`).join(' · ');
        return `${a.countsLine}. Most recent: ${recent || 'nothing yet'}.`;
      },
    },
    {
      question: 'Which data does it depend on?',
      keywords: ['data', 'feed', 'depend', 'fresh'],
      answer: (vm) => {
        const a = vm.agents[id];
        return a.feeds.map((f) => `${f.name} · updated ${fmtAge(f.lastUpdatedMs, vm.nowMs)} ago${f.late ? ' · late' : ''}`).join(' · ');
      },
    },
  ];
}

export function scriptsFor(sel: Selection): { scope: string; placeholder: string; scripts: Scripted[] } {
  if (!sel) return { scope: 'Monitoring Agent', placeholder: 'Ask the Monitoring Agent about feeds or agents', scripts: MONITOR };
  if (sel.kind === 'agent') return { scope: `${sel.id}`, placeholder: `Ask about the ${agentName(sel.id)}`, scripts: agentScripts(sel.id) };
  switch (sel.id) {
    case 'DEC-0911-01':
      return { scope: sel.id, placeholder: 'Ask about the Infosys proposal', scripts: INFOSYS };
    case 'DEC-0911-02':
      return { scope: sel.id, placeholder: 'Ask about the HDFC Bank verdict', scripts: HDFC };
    case 'BRK-0910-01':
      return { scope: sel.id, placeholder: 'Ask about the Axis Bank mismatch', scripts: AXIS };
    default:
      if (sel.id.startsWith('FEED-')) return { scope: sel.id, placeholder: 'Ask about the late feed', scripts: FEED_LATE };
      if (sel.id.startsWith('LIMIT-')) return { scope: sel.id, placeholder: 'Ask about the broken limit', scripts: LIMIT_OVER };
      return { scope: sel.id, placeholder: 'Ask about this item', scripts: MONITOR };
  }
}

function agentName(id: AgentId): string {
  const names: Record<AgentId, string> = {
    research: 'Research Agent',
    portfolio: 'Portfolio Agent',
    risk: 'Risk Agent',
    compliance: 'Compliance Agent',
    execution: 'Execution Agent',
    operations: 'Operations Agent',
    monitoring: 'Monitoring Agent',
  };
  return names[id];
}

/** Match free text to a scripted answer, or fall back. */
export function answerFor(text: string, sel: Selection, vm: ViewModel): string {
  const { scripts } = scriptsFor(sel);
  const q = text.toLowerCase();
  let best: Scripted | null = null;
  let bestScore = 0;
  for (const s of scripts) {
    const score = s.keywords.filter((k) => q.includes(k)).length;
    if (score > bestScore) {
      best = s;
      bestScore = score;
    }
  }
  if (best && bestScore > 0) return best.answer(vm);
  return `I answer from the record for the selected item, and I do not summarise disputed evidence. Try one of the suggested questions, or open the full trail below.`;
}
